-- ============================================================
-- B&I Controls Hub — Complete Oracle DDL
-- Version: 3.0  |  Date: April 2026
-- Schema: BIC (or your designated schema)
-- 
-- Tables created:
--   1. BI_CHAT_SESSION       — AI chat sessions per user/scorecard
--   2. BI_CHAT_HISTORY       — Individual chat messages + tokens
--   3. BI_API_AUDIT          — Immutable compliance audit log
--   4. BI_SNAPSHOT_LOG       — Tableau fetch audit trail
--   5. BI_DATA_CONTEXT       — Cached Tableau data for LLM context
--
-- INSTRUCTIONS: See ORACLE_SETUP.md for execution steps
-- ============================================================

-- ── SAFETY: check existing tables before running ────────────────────────────
-- Uncomment and run this block first to see what exists:
-- SELECT TABLE_NAME FROM USER_TABLES
--   WHERE TABLE_NAME IN ('BI_CHAT_SESSION','BI_CHAT_HISTORY',
--         'BI_API_AUDIT','BI_SNAPSHOT_LOG','BI_DATA_CONTEXT')
--   ORDER BY TABLE_NAME;

-- ── SET OUTPUT MODE ─────────────────────────────────────────────────────────
SET DEFINE OFF;
SET SERVEROUTPUT ON SIZE UNLIMITED;


-- ============================================================
-- TABLE 1: BI_CHAT_SESSION
-- One row per user × scorecard × conversation
-- ============================================================

CREATE TABLE BI_CHAT_SESSION (
    SESSION_ID       VARCHAR2(64)    NOT NULL,
    USER_ID          VARCHAR2(50)    NOT NULL,
    SCORECARD_ID     VARCHAR2(100)   NOT NULL,
    SCORECARD_NAME   VARCHAR2(200),
    LEGAL_ENTITY     VARCHAR2(20),           -- CGML | CGMSE | CGME | ALL
    REGION           VARCHAR2(20),           -- UK | SGP | CEP
    DASHBOARD_TYPE   VARCHAR2(50),           -- kri_scorecard | dcrm_mixed | generic
    CREATED_DT       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_ACTIVE_DT   TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    MESSAGE_COUNT    NUMBER(6,0)     DEFAULT 0 NOT NULL,
    STATUS           VARCHAR2(20)    DEFAULT 'ACTIVE' NOT NULL,
    --
    CONSTRAINT PK_BI_CHAT_SESSION PRIMARY KEY (SESSION_ID),
    CONSTRAINT CK_BI_SESS_STATUS  CHECK (STATUS IN ('ACTIVE','CLOSED','EXPIRED')),
    CONSTRAINT CK_BI_SESS_ENTITY  CHECK (LEGAL_ENTITY IN ('CGML','CGMSE','CGME','ALL') OR LEGAL_ENTITY IS NULL)
);

COMMENT ON TABLE  BI_CHAT_SESSION              IS 'B&I Controls Hub: AI chat sessions per user per scorecard';
COMMENT ON COLUMN BI_CHAT_SESSION.SESSION_ID   IS 'UUID v4 generated by application';
COMMENT ON COLUMN BI_CHAT_SESSION.USER_ID      IS 'Citi WWID (e.g. PG23137)';
COMMENT ON COLUMN BI_CHAT_SESSION.SCORECARD_ID IS 'Internal scorecard ID (e.g. uk-kri, crmr-cde)';
COMMENT ON COLUMN BI_CHAT_SESSION.LEGAL_ENTITY IS 'Controlling legal entity: CGML|CGMSE|CGME|ALL';
COMMENT ON COLUMN BI_CHAT_SESSION.DASHBOARD_TYPE IS 'Auto-detected: kri_scorecard|dcrm_mixed|generic';
COMMENT ON COLUMN BI_CHAT_SESSION.STATUS       IS 'ACTIVE|CLOSED|EXPIRED';

CREATE INDEX IDX_BI_SESS_USER   ON BI_CHAT_SESSION (USER_ID);
CREATE INDEX IDX_BI_SESS_SC     ON BI_CHAT_SESSION (SCORECARD_ID);
CREATE INDEX IDX_BI_SESS_ENTITY ON BI_CHAT_SESSION (LEGAL_ENTITY);
CREATE INDEX IDX_BI_SESS_DT     ON BI_CHAT_SESSION (CREATED_DT);
CREATE INDEX IDX_BI_SESS_STATUS ON BI_CHAT_SESSION (STATUS);


-- ============================================================
-- TABLE 2: BI_CHAT_HISTORY
-- Every message (user + assistant) in every session
-- ============================================================

CREATE TABLE BI_CHAT_HISTORY (
    ID               NUMBER          GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    SESSION_ID       VARCHAR2(64)    NOT NULL,
    USER_ID          VARCHAR2(50)    NOT NULL,
    SCORECARD_ID     VARCHAR2(100)   NOT NULL,
    ROLE             VARCHAR2(20)    NOT NULL,   -- user | assistant
    CONTENT          CLOB            NOT NULL,
    CHART_TYPE       VARCHAR2(30),               -- bar|line|pie|kpi|table|scorecard|text
    MODEL_VERSION    VARCHAR2(100),              -- e.g. gemini-1.5-pro / pandas-rules
    QUERY_METHOD     VARCHAR2(20),               -- llm | rules | hybrid
    INPUT_TOKENS     NUMBER(8,0),
    OUTPUT_TOKENS    NUMBER(8,0),
    RESPONSE_TIME_MS NUMBER(8,0),
    CONFIDENCE       NUMBER(4,3),               -- 0.000 – 1.000 (for rule-based answers)
    CREATED_DT       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    --
    CONSTRAINT FK_BI_HIST_SESSION FOREIGN KEY (SESSION_ID)
        REFERENCES BI_CHAT_SESSION (SESSION_ID),
    CONSTRAINT CK_BI_HIST_ROLE CHECK (ROLE IN ('user','assistant','system')),
    CONSTRAINT CK_BI_HIST_METHOD CHECK (QUERY_METHOD IN ('llm','rules','hybrid') OR QUERY_METHOD IS NULL),
    CONSTRAINT CK_BI_HIST_CONF CHECK (CONFIDENCE BETWEEN 0 AND 1 OR CONFIDENCE IS NULL)
);

COMMENT ON TABLE  BI_CHAT_HISTORY                  IS 'B&I Controls Hub: individual chat messages';
COMMENT ON COLUMN BI_CHAT_HISTORY.ROLE             IS 'user|assistant|system';
COMMENT ON COLUMN BI_CHAT_HISTORY.CHART_TYPE       IS 'Chart type returned: bar|line|pie|doughnut|kpi|table|scorecard|text';
COMMENT ON COLUMN BI_CHAT_HISTORY.MODEL_VERSION    IS 'LLM model or pandas-rules';
COMMENT ON COLUMN BI_CHAT_HISTORY.QUERY_METHOD     IS 'llm=Gemini | rules=pandas | hybrid=rules+llm';
COMMENT ON COLUMN BI_CHAT_HISTORY.CONFIDENCE       IS 'Rule-based confidence score 0-1 (NULL for LLM)';

CREATE INDEX IDX_BI_HIST_SESSION ON BI_CHAT_HISTORY (SESSION_ID);
CREATE INDEX IDX_BI_HIST_USER    ON BI_CHAT_HISTORY (USER_ID);
CREATE INDEX IDX_BI_HIST_SC      ON BI_CHAT_HISTORY (SCORECARD_ID);
CREATE INDEX IDX_BI_HIST_DT      ON BI_CHAT_HISTORY (CREATED_DT);
CREATE INDEX IDX_BI_HIST_METHOD  ON BI_CHAT_HISTORY (QUERY_METHOD);


-- ============================================================
-- TABLE 3: BI_API_AUDIT
-- Immutable compliance log — every API call recorded
-- ============================================================

CREATE TABLE BI_API_AUDIT (
    ID               NUMBER          GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    ENDPOINT         VARCHAR2(200)   NOT NULL,
    HTTP_METHOD      VARCHAR2(10)    NOT NULL,
    USER_ID          VARCHAR2(50),
    SCORECARD_ID     VARCHAR2(100),
    STATUS_CODE      NUMBER(3,0),
    RESPONSE_TIME_MS NUMBER(8,0),
    ERROR_MESSAGE    VARCHAR2(2000),
    IP_ADDRESS       VARCHAR2(50),
    REQUEST_BODY_LEN NUMBER(10,0),   -- bytes, not content
    CREATED_DT       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    --
    CONSTRAINT CK_BI_AUDIT_METHOD CHECK (HTTP_METHOD IN ('GET','POST','PUT','DELETE','PATCH'))
);

COMMENT ON TABLE  BI_API_AUDIT                    IS 'B&I Controls Hub: immutable API call audit (compliance)';
COMMENT ON COLUMN BI_API_AUDIT.REQUEST_BODY_LEN   IS 'Length of request body in bytes — content not stored for compliance';

-- Partial index: only index error rows for fast error analysis
CREATE INDEX IDX_BI_AUDIT_DT      ON BI_API_AUDIT (CREATED_DT);
CREATE INDEX IDX_BI_AUDIT_USER    ON BI_API_AUDIT (USER_ID);
CREATE INDEX IDX_BI_AUDIT_SC      ON BI_API_AUDIT (SCORECARD_ID);
CREATE INDEX IDX_BI_AUDIT_STATUS  ON BI_API_AUDIT (STATUS_CODE);
CREATE INDEX IDX_BI_AUDIT_ENDPT   ON BI_API_AUDIT (ENDPOINT);


-- ============================================================
-- TABLE 4: BI_SNAPSHOT_LOG
-- Audit trail for every Tableau snapshot fetch (PNG/PDF/CSV)
-- ============================================================

CREATE TABLE BI_SNAPSHOT_LOG (
    ID               NUMBER          GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    VIEW_ID          VARCHAR2(200)   NOT NULL,   -- Tableau View UUID
    SCORECARD_ID     VARCHAR2(100),
    USER_ID          VARCHAR2(50),
    FILE_TYPE        VARCHAR2(10)    NOT NULL,   -- PNG | PDF | CSV | JSON
    SUCCESS          CHAR(1)         DEFAULT 'Y' NOT NULL,
    CACHED           CHAR(1)         DEFAULT 'N' NOT NULL,   -- was it served from cache?
    ERROR_MESSAGE    VARCHAR2(500),
    FILE_SIZE_BYTES  NUMBER(12,0),
    RESPONSE_TIME_MS NUMBER(8,0),
    API_VERSION      VARCHAR2(10),               -- e.g. 3.1
    CREATED_DT       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    --
    CONSTRAINT CK_BI_SNAP_TYPE    CHECK (FILE_TYPE IN ('PNG','PDF','CSV','JSON','EXCEL')),
    CONSTRAINT CK_BI_SNAP_SUCCESS CHECK (SUCCESS IN ('Y','N')),
    CONSTRAINT CK_BI_SNAP_CACHED  CHECK (CACHED  IN ('Y','N'))
);

COMMENT ON TABLE  BI_SNAPSHOT_LOG              IS 'B&I Controls Hub: Tableau snapshot fetch audit trail';
COMMENT ON COLUMN BI_SNAPSHOT_LOG.VIEW_ID      IS 'Tableau View UUID (e.g. c69d5ca6-1849-4542-...)';
COMMENT ON COLUMN BI_SNAPSHOT_LOG.CACHED       IS 'Y = served from 5-minute in-memory cache';
COMMENT ON COLUMN BI_SNAPSHOT_LOG.API_VERSION  IS 'Tableau REST API version used (3.1)';

CREATE INDEX IDX_BI_SNAP_SC   ON BI_SNAPSHOT_LOG (SCORECARD_ID);
CREATE INDEX IDX_BI_SNAP_DT   ON BI_SNAPSHOT_LOG (CREATED_DT);
CREATE INDEX IDX_BI_SNAP_VIEW ON BI_SNAPSHOT_LOG (VIEW_ID);
CREATE INDEX IDX_BI_SNAP_TYPE ON BI_SNAPSHOT_LOG (FILE_TYPE);


-- ============================================================
-- TABLE 5: BI_DATA_CONTEXT
-- Cached Tableau data chunks for LLM context injection
-- Replaces/reduces expensive re-extraction from Tableau
-- ============================================================

CREATE TABLE BI_DATA_CONTEXT (
    ID               NUMBER          GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    SOURCE_ID        VARCHAR2(200)   NOT NULL,   -- internal scorecard ID
    SOURCE_NAME      VARCHAR2(500),
    CHUNK_ID         VARCHAR2(50)    NOT NULL,   -- MD5 hash of content
    CHUNK_TYPE       VARCHAR2(50)    NOT NULL,   -- summary|schema|stats|rows|visual
    CONTENT          CLOB            NOT NULL,
    TOKEN_COUNT      NUMBER(8,0)     DEFAULT 0,
    METADATA         CLOB,                       -- JSON: filters, view_id, extracted_at
    TOTAL_ROWS       NUMBER(10,0)    DEFAULT 0,
    TOTAL_COLS       NUMBER(5,0)     DEFAULT 0,
    DASHBOARD_TYPE   VARCHAR2(50),               -- kri_scorecard|dcrm_mixed|generic
    VISUAL_COUNT     NUMBER(4,0)     DEFAULT 0,  -- number of visuals detected
    EXTRACTED_DT     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    EXPIRES_DT       TIMESTAMP,                  -- NULL = never expires
    --
    CONSTRAINT UQ_BI_CTX_CHUNK UNIQUE (SOURCE_ID, CHUNK_ID),
    CONSTRAINT CK_BI_CTX_TYPE  CHECK (CHUNK_TYPE IN ('summary','schema','stats','rows','visual','kpi'))
);

COMMENT ON TABLE  BI_DATA_CONTEXT                IS 'B&I Controls Hub: Tableau data chunks cached for LLM injection';
COMMENT ON COLUMN BI_DATA_CONTEXT.SOURCE_ID      IS 'Internal scorecard ID (e.g. uk-kri, crmr-cde)';
COMMENT ON COLUMN BI_DATA_CONTEXT.CHUNK_ID       IS 'MD5 hash of content (first 12 chars)';
COMMENT ON COLUMN BI_DATA_CONTEXT.CHUNK_TYPE     IS 'summary|schema|stats|rows|visual|kpi';
COMMENT ON COLUMN BI_DATA_CONTEXT.METADATA       IS 'JSON: {view_id, filters, extracted_at, dashboard_type}';
COMMENT ON COLUMN BI_DATA_CONTEXT.DASHBOARD_TYPE IS 'kri_scorecard|dcrm_mixed|generic';
COMMENT ON COLUMN BI_DATA_CONTEXT.VISUAL_COUNT   IS 'Number of visual elements detected by VisualDashboardExtractor';
COMMENT ON COLUMN BI_DATA_CONTEXT.EXPIRES_DT     IS 'Cache expiry — NULL means never expires';

CREATE INDEX IDX_BI_CTX_SOURCE  ON BI_DATA_CONTEXT (SOURCE_ID);
CREATE INDEX IDX_BI_CTX_EXPIRES ON BI_DATA_CONTEXT (EXPIRES_DT);
CREATE INDEX IDX_BI_CTX_TYPE    ON BI_DATA_CONTEXT (CHUNK_TYPE);
CREATE INDEX IDX_BI_CTX_DTYPE   ON BI_DATA_CONTEXT (DASHBOARD_TYPE);
CREATE INDEX IDX_BI_CTX_DT      ON BI_DATA_CONTEXT (EXTRACTED_DT);


-- ============================================================
-- VERIFICATION QUERIES
-- Run these after creation to confirm all objects exist
-- ============================================================

-- 1. Check all tables were created
SELECT TABLE_NAME, NUM_ROWS
FROM   USER_TABLES
WHERE  TABLE_NAME IN (
    'BI_CHAT_SESSION', 'BI_CHAT_HISTORY',
    'BI_API_AUDIT', 'BI_SNAPSHOT_LOG', 'BI_DATA_CONTEXT'
)
ORDER BY TABLE_NAME;

-- 2. Check all indexes
SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS
FROM   USER_INDEXES
WHERE  TABLE_NAME IN (
    'BI_CHAT_SESSION', 'BI_CHAT_HISTORY',
    'BI_API_AUDIT', 'BI_SNAPSHOT_LOG', 'BI_DATA_CONTEXT'
)
ORDER BY TABLE_NAME, INDEX_NAME;

-- 3. Check all constraints
SELECT CONSTRAINT_NAME, TABLE_NAME, CONSTRAINT_TYPE, STATUS
FROM   USER_CONSTRAINTS
WHERE  TABLE_NAME IN (
    'BI_CHAT_SESSION', 'BI_CHAT_HISTORY',
    'BI_API_AUDIT', 'BI_SNAPSHOT_LOG', 'BI_DATA_CONTEXT'
)
ORDER BY TABLE_NAME, CONSTRAINT_TYPE;

-- 4. Check column details for key table
DESC BI_CHAT_HISTORY;


-- ============================================================
-- OPTIONAL: GRANTS (if running as DBA for a different schema)
-- Replace BIUSER with your actual application user
-- ============================================================
-- GRANT SELECT, INSERT, UPDATE ON BI_CHAT_SESSION TO BIUSER;
-- GRANT SELECT, INSERT, UPDATE ON BI_CHAT_HISTORY  TO BIUSER;
-- GRANT SELECT, INSERT         ON BI_API_AUDIT      TO BIUSER;
-- GRANT SELECT, INSERT         ON BI_SNAPSHOT_LOG   TO BIUSER;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON BI_DATA_CONTEXT TO BIUSER;


-- ============================================================
-- MAINTENANCE QUERIES (run periodically or schedule)
-- ============================================================

-- Expire old cache entries (run daily via DBMS_SCHEDULER or manually)
-- DELETE FROM BI_DATA_CONTEXT WHERE EXPIRES_DT < SYSTIMESTAMP;
-- COMMIT;

-- Archive old audit records (keep last 90 days)
-- DELETE FROM BI_API_AUDIT WHERE CREATED_DT < SYSTIMESTAMP - INTERVAL '90' DAY;
-- COMMIT;

-- Close stale sessions (inactive > 7 days)
-- UPDATE BI_CHAT_SESSION
--   SET STATUS = 'EXPIRED'
-- WHERE STATUS = 'ACTIVE'
--   AND LAST_ACTIVE_DT < SYSTIMESTAMP - INTERVAL '7' DAY;
-- COMMIT;


-- ============================================================
-- ROLLBACK SCRIPT (if you need to undo everything)
-- ============================================================
-- Run in this exact order to respect FK constraints:
-- DROP TABLE BI_CHAT_HISTORY  CASCADE CONSTRAINTS;
-- DROP TABLE BI_CHAT_SESSION  CASCADE CONSTRAINTS;
-- DROP TABLE BI_API_AUDIT     CASCADE CONSTRAINTS;
-- DROP TABLE BI_SNAPSHOT_LOG  CASCADE CONSTRAINTS;
-- DROP TABLE BI_DATA_CONTEXT  CASCADE CONSTRAINTS;


-- ============================================================
PROMPT 
PROMPT ============================================================
PROMPT  B&I Controls Hub DDL complete.
PROMPT  5 tables created with indexes, constraints, and comments.
PROMPT  Run verification queries above to confirm.
PROMPT ============================================================
