-- B&I Controls Hub — Oracle Schema (run once)
-- All tables are ADDITIVE — no existing tables modified

CREATE TABLE BI_CHAT_SESSION (
    SESSION_ID      VARCHAR2(64)    NOT NULL,
    USER_ID         VARCHAR2(50)    NOT NULL,
    SCORECARD_ID    VARCHAR2(100)   NOT NULL,
    SCORECARD_NAME  VARCHAR2(200),
    CREATED_DT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    LAST_ACTIVE_DT  TIMESTAMP       DEFAULT SYSTIMESTAMP,
    MESSAGE_COUNT   NUMBER          DEFAULT 0,
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE',
    CONSTRAINT PK_BI_CHAT_SESSION PRIMARY KEY (SESSION_ID)
);
CREATE INDEX IDX_CHAT_SESSION_USER ON BI_CHAT_SESSION(USER_ID);
CREATE INDEX IDX_CHAT_SESSION_SC   ON BI_CHAT_SESSION(SCORECARD_ID);
CREATE INDEX IDX_CHAT_SESSION_DT   ON BI_CHAT_SESSION(CREATED_DT);

CREATE TABLE BI_CHAT_HISTORY (
    ID               NUMBER         GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SESSION_ID       VARCHAR2(64)   NOT NULL,
    USER_ID          VARCHAR2(50)   NOT NULL,
    SCORECARD_ID     VARCHAR2(100)  NOT NULL,
    ROLE             VARCHAR2(20)   NOT NULL,
    CONTENT          CLOB           NOT NULL,
    MODEL_VERSION    VARCHAR2(100),
    INPUT_TOKENS     NUMBER,
    OUTPUT_TOKENS    NUMBER,
    RESPONSE_TIME_MS NUMBER,
    CREATED_DT       TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_CHAT_HIST_SESSION FOREIGN KEY (SESSION_ID) REFERENCES BI_CHAT_SESSION(SESSION_ID)
);
CREATE INDEX IDX_CHAT_HIST_SESSION ON BI_CHAT_HISTORY(SESSION_ID);
CREATE INDEX IDX_CHAT_HIST_USER    ON BI_CHAT_HISTORY(USER_ID);
CREATE INDEX IDX_CHAT_HIST_SC      ON BI_CHAT_HISTORY(SCORECARD_ID);
CREATE INDEX IDX_CHAT_HIST_DT      ON BI_CHAT_HISTORY(CREATED_DT);

CREATE TABLE BI_API_AUDIT (
    ID               NUMBER         GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ENDPOINT         VARCHAR2(200)  NOT NULL,
    HTTP_METHOD      VARCHAR2(10)   NOT NULL,
    USER_ID          VARCHAR2(50),
    SCORECARD_ID     VARCHAR2(100),
    STATUS_CODE      NUMBER,
    RESPONSE_TIME_MS NUMBER,
    ERROR_MESSAGE    VARCHAR2(2000),
    IP_ADDRESS       VARCHAR2(50),
    CREATED_DT       TIMESTAMP      DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_API_AUDIT_DT ON BI_API_AUDIT(CREATED_DT);

CREATE TABLE BI_SNAPSHOT_LOG (
    ID               NUMBER         GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VIEW_ID          VARCHAR2(200)  NOT NULL,
    SCORECARD_ID     VARCHAR2(100),
    USER_ID          VARCHAR2(50),
    FILE_TYPE        VARCHAR2(10)   NOT NULL,
    SUCCESS          CHAR(1)        DEFAULT 'Y',
    ERROR_MESSAGE    VARCHAR2(500),
    FILE_SIZE_BYTES  NUMBER,
    RESPONSE_TIME_MS NUMBER,
    CREATED_DT       TIMESTAMP      DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_SNAP_LOG_SC ON BI_SNAPSHOT_LOG(SCORECARD_ID);
CREATE INDEX IDX_SNAP_LOG_DT ON BI_SNAPSHOT_LOG(CREATED_DT);
